### ISSUE TITLE
最大回撤期bug，运行出的结果如下

### ISSUE THREAD

**Issue by gglive** [quantOS-org/JAQS#12]
Term | Value
-- | --
Beta | 0.943
Maximum Drawdown (%) | 1.413
Maximum Drawdown start | 20171218
Maximum Drawdown end | 20171206

**Comment by brillliantz** [comment]
BUG确认，已修复，见[commit](https://github.com/quantOS-org/JAQS/commit/6e4b7dfc4194e07945521c892680fca2dd09e2ab)
