### ISSUE TITLE
这个回测是不是因为没有复权数据的问题

### ISSUE THREAD

**Issue by royburns** [quantOS-org/JAQS#13]
这个回测是不是因为没有复权数据的问题
有解决方法吗

props = {
    # "symbol": "rb1710.SHF",
    # "symbol": "002050.SZ",
    "symbol": "002027.SZ",
    'benchmark': '000300.SH',
    "start_date": 20170101,
    "end_date": 20171130,
    "buffersize": 7,
    "k1": 0.2,
    "k2": 0.2,
    "bar_type": "1M",
    "init_balance": 3e4,
    "commission_rate": 0.0
}

![image](https://user-images.githubusercontent.com/652375/34326546-1f88e9de-e8ea-11e7-9b4a-0577a960b594.png)

**Comment by brillliantz** [comment]
是的，已经解决，增加了事件驱动框架的除权除息。请更新测试
