### ISSUE TITLE
dataApi.query无法获取指数相关数据

### ISSUE THREAD

**Issue by walkacross** [quantOS-org/JAQS#14]
(1)无法获取指数成分股数据， df返回为None
df, msg = api.query(
                  view="lb.indexCons",
                  fields="",
                  filter="index_code=399001",
                  data_format='pandas')
(2)无法获取行业数据，df返回为None
df, msg = api.query(
                  view="lb.secIndustry",
                  fields="",
                  filter="industry1_name=金融&industry2_name=金融&industry_src=中证",
                  data_format='pandas')

**Comment by brillliantz** [comment]
指数成分
```python
df, msg = ds.query(
view="lb.indexCons",
fields="",
filter="index_code=399001.SZ&start_date=20170101&end_date=20170501",)
```
这个是文档问题，已解决

行业数据
```python
df, msg = ds.query(
view="lb.secIndustry",
fields="",
filter=u"symbol=600519.SH&industry_src=中证指数有限公司")
```
