### ISSUE TITLE
analyze 生成的报告中关于最大回撤的起止时间反了

### ISSUE THREAD

**Issue by slashqiang** [quantOS-org/JAQS#15]
试了几次都是反的，如下：

Strategy Risk Metrics

Term | Value
-- | --
Beta | nan
Maximum Drawdown (%) | 33.09
Maximum Drawdown start | 20160215
Maximum Drawdown end | 20150422

**Comment by PKUJohnson** [comment]
这个在最新的版本已经修正，请下载master分支的最新版本，谢谢！
