### ISSUE TITLE
bar和bar_quote的区别？

### ISSUE THREAD

**Issue by semigodking** [quantOS-org/JAQS#32]
data api的说明中这两个完全一样啊。代码里的说明也几乎完全一样。
既然是一样的东西，为什么要用两个函数？
bar | 提供历史分时数据和实时分时数据 | 支持的范围包括：1分钟、5分钟、15分钟
-- | -- | --
bar_quote | 提供历史分时数据和实时分时数据 | 支持的范围包括：1分钟、5分钟、15分钟

**Comment by PKUJohnson** [comment]
是有区别的。bar_quote包含了最后一个tick的bid/ask信息。
