### ISSUE TITLE
数据api中，fields为“”时并不返回全部字段的数据。

### ISSUE THREAD

**Issue by OneGIl** [quantOS-org/JAQS#4]
在数据api文档中关于输入参数是这样写的：
> fields | string | 需要返回字段，多字段以','隔开；为""时返回所有字段

目前只测试了证券基础信息和交易日历的这2个API，发现如果fields参数设置为空字符串的话，并不会按照文档所说的返回所有字段的数据。
1.证券基础信息API只返回list_date，name，symbol这3个字段。
2.交易日历API只返回istradeday，trade_date这2个字段。

**Comment by brillliantz** [comment]
对于行情数据，`fields`为`”“`时返回默认**可显示**字段；
对于参考数据，`fields`为`”“`时返回**所有**字段。

文档已更新，谢谢提出。
