### ISSUE TITLE
历史日内 bar 数据问题

### ISSUE THREAD

**Issue by gaizoule** [quantOS-org/JAQS#5]
目前数据接口只能一天一天取历史日内的 bar 数据，希望增加一个函数，能够取一段时间的日内的 bar 数据，同时支持复权。

**Comment by brillliantz** [comment]
目前，历史分钟线只支持**每日分别取**，且日内数据为**无复权**的原始数据。

你提到的特性会讨论增加。

**Comment by brillliantz** [comment]
`bar`暂时不会支持复权
