### ISSUE TITLE
在两台不同的电脑上，回测结果会不同

### ISSUE THREAD

**Issue by dazekey** [quantOS-org/JAQS#52]
在两台不同的电脑上，回测结果会不同
本来以为是python 2和python 3的版本问题，后来换了台电脑，都是Python2，结果遇到了同样的问题。
对比发现，trades.csv的结果都是一样的。
但是在生成报告时，生成的daily_position.csv和returns.csv的结果截然不同

**Comment by dazekey** [comment]
solved, 多次重装尝试后，发现是pandas版本的问题，用conda 安装pandas就正常了，不能用pip安装，匪夷所思。。。。

**Comment by listplot3d** [comment]
如果是pandas版本的问题，怎么确定conda的那个pandas就是对的？有可能是pip的版本才是对的呢？
