### ISSUE TITLE
加载数据模块 出错 请指教

### ISSUE THREAD

**Issue by kingismybrother** [quantOS-org/JAQS#6]
输入：api.login("phone", "token")
输出：(None, '-1000,login failure: Map(username -> phone, password -> token)')

不好意思 打搅了 我不是很懂接口的问题 请问这个是怎么回事，该怎样解决

**Comment by brillliantz** [comment]
代码中的`phone`和`token`分别是你的手机号和API令牌，用于获取数据前的登录验证。令牌通过注册用户即可获取，在[这里](https://www.quantos.org/cas/register.html)注册，使用说明见[快速入门](https://www.quantos.org/courses/index.html)。
