### ISSUE TITLE
quantOS网页打不开

### ISSUE THREAD

**Issue by yuba316** [quantOS-org/JAQS#65]
什么情况？
今天早上想获取数据，结果发现连网站都打不开了？？？
10.8日早上，是国庆放假到现在都没好么？？？我昏了呀。
求求各位处理一下，臣不胜受恩感激！

**Comment by PKUJohnson** [comment]
已经恢复了

**Comment by yuba316** [comment]
可是我昨天网站能登陆了，获取下来的实时行情都是nan值，好难受唔……
求求大佬救助唔。臣不胜受恩感激！
