### ISSUE TITLE
tradeapi 出现‘createWsUrl’错误

### ISSUE THREAD

**Issue by JeiWang** [quantOS-org/JAQS#8]
from jaqs.trade.tradeapi import TradeApi
tapi = TradeApi(addr="tcp://gw.quantos.org:8901")
Exception cannot import name 'createWsUrl'
TradeApi: _on_connected

之前会提示少了jrpc包，安装了jrpd包之后就提示上述问题

环境：max os 10.13   python 3.6    jaqs  0.6.6

**Comment by brillliantz** [comment]
卸载jrpc即可，这个包是不需要的，提示信息会尽快去掉

**Comment by snsmqing** [comment]
好像不行哦，还是会提示安装jrpc，并且不能断续。
Python 2.7.14 |Anaconda, Inc.| [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tradeapi import TradeApi
>>> api = TradeApi(addr="tcp://gw.quantos.org:8901")
Exception No module named jrpc
>>> TradeApi: _on_connected
